[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana01 = "51yDLUXvtS8b3e9dsiDvgsQDRgyayCMqMnzY3JU6JDCF"
solana02 = "6zZeL7zABHPj2H3RsfAm8mqTPqjRMKdsZbBMg5NxnSof"

[programs.testnet]
solana01 = "51yDLUXvtS8b3e9dsiDvgsQDRgyayCMqMnzY3JU6JDCF"
solana02 = "6zZeL7zABHPj2H3RsfAm8mqTPqjRMKdsZbBMg5NxnSof"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[scripts]
done = "anchor build -p solana01 && anchor deploy -p solana01 && cp ./target/idl/my_program.json ./solana-frontend/src && cp ./target/types/my_program.ts ./solana-frontend/src && cd solana-frontend && npm run build && cd .."
test = "npm run test"
